version: "3.7"

services:
  postgres:
    image: postgres:14.1-alpine
    restart: always
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    command:
      ["postgres", "-c", "log_statement=all", "-c", "log_duration=on"]
