[tool.black]
exclude = "migrations"

[tool.flake8]
# Flake8 doesn't support pyproject.toml yet (see .flake8 file):
# https://gitlab.com/pycqa/flake8/issues/428
max-line-length = 88

[tool.isort]
line_length = 88
force_single_line = "1"
known_first_party = ["app", "tests"]
default_section = "THIRDPARTY"
skip = "*/migrations/*"
